### ISSUE TITLE
Error annotations written over code

### ISSUE THREAD

**Issue by CipherpunkChris** [ryanfleury/4coder_fleury#2]
The annotations are rendered right on top of code in some cases, making both the annotation and the code very difficult to read. Also, the cursor in the compilation buffer jump-list is missing and I wasn't sure if that was intentional.

![error_annotations](https://user-images.githubusercontent.com/21264420/75171934-b149e480-56e9-11ea-91dc-823405cbad25.png)

**Comment by ryanfleury** [comment]
Ah, yeah, I was running into this the other day—I will need to fix up the layout here. For now you can disable the annotations by commenting out the code at line 1366 in 4coder_fleury.cpp. I'll address this soon.

The missing cursor has to do with the new cursor rendering—I will adjust the cursor rendering soon to make sure cursor positions are rendered in every view, including inactive ones.

**Comment by ryanfleury** [comment]
Should be fixed in the latest commit. Let me know if you have any other issues.
