### ISSUE TITLE
Scope annotations issues

### ISSUE THREAD

**Issue by mrmixer** [ryanfleury/4coder_fleury#6]
I used your code as a base for adding scope annotations. But it doesn't handle "case" scopes. Maybe you don't use curly braces on those, but a simple modification can make it work.

In 4coder_fleury_brace.cpp, in the function Fleury4RenderCloseBraceAnnotation in lines 118 to 120.

This code
`else if(paren_nest == 0 &&
          (token->kind == TokenBaseKind_ScopeClose ||
          token->kind == TokenBaseKind_StatementClose))`

can be changed to
`else if(paren_nest == 0 &&
          (token->kind == TokenBaseKind_ScopeClose ||
          (token->kind == TokenBaseKind_StatementClose && token->sub_kind != TokenCppKind_Colon)))`

**Comment by mrmixer** [comment]
In addition, the token iterator decrementation should be before the token is read, and initialize the iterator to range.start instead of range.start -1. Otherwise you may loose a valid token. For example if the first thing in a file is
`CUSTOM_COMMAND_SIG( custom_startup ) {`
with the current code, the iterator will at some point read CUSTOM_COMMAND_SIG, but the decrement will fail since there are no more token, and you won't process the token which in term causes no annotation to be displayed.

A small detail about that piece of code: the if that should be entered to set start_token could be written with the paren_nest == 0 as the first thing in the if to keep consistency with the if above and make it clear that it is a "prerequisite". I just found that to be more readable.

**Comment by ryanfleury** [comment]
Fixed this up in the most recent commit. Now works for case labels, and now will defer the decrement until after processing.
