### ISSUE TITLE
Small fix for Fleury4RenderBraceLines

### ISSUE THREAD

**Issue by aolo2** [ryanfleury/4coder_fleury#8]
Brace lines seem to be drawn at x = `view_get_screen_rect(app, view).x0 + ...`, however this doesn't seem to work with the line number margin enabled. The offset taking the margin into account is already there, it's the last argument (as of 4.1.6) of `default_render_buffer`: `Rect_f32 rect`. I tried passing it to your routine and rendering at x = `rect.x0 + ...`, and it works great both with and without the line number margin.

**Comment by aolo2** [comment]
Also, the current code draws a `line_height` tall line when the cursor is inside a brace initializer, e.g:
```
|  struct foo = { [CURSOR_HERE] };
^ line here
```
This is fixed by adding a threshold for the minimal difference between braces:
```
if (abs_f32(range_start_rect.y0 - range_end_rect.y0) > 0.01f) {
    float y_start = 0;
    float y_end = 10000;
    ...
```

**Comment by ryanfleury** [comment]
Sorry for the late response... This should be fixed sometime in the last 6 months.
